// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/getting-started',
        'guides/architecture',
        'guides/application-setup',
        'guides/http-requests',
        'guides/state-routing',
        'guides/forms-fields',
        'guides/event-system',
        'guides/dom-manipulation',
        'guides/storage',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'api'},
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/class-hierarchy',
        'reference/glossary',
      ],
    },
  ],
};

module.exports = sidebars;
